# -*- coding: utf-8 -*-
"""cr3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IpeNp4yXgHu5NIWj7aZUdU90F3xCusRg
"""

#from google.colab import files
#uploaded = files.upload()

#!pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np
import pickle

# Load the model
with open('rf_model_heart.pkl', 'rb') as file:
    model = pickle.load(file)

st.title("Crop Recommendation App")

st.sidebar.header("Soil and Climate Data")

def user_input_features():
    N = st.sidebar.number_input('Nitrogen (N)', min_value=0)
    P = st.sidebar.number_input('Phosphorus (P)', min_value=0)
    K = st.sidebar.number_input('Potassium (K)', min_value=0)
    temperature = st.sidebar.number_input('Temperature (°C)', min_value=0.0)
    humidity = st.sidebar.number_input('Humidity (%)', min_value=0.0, max_value=100.0)
    ph = st.sidebar.number_input('Soil pH', min_value=0.0, max_value=14.0)
    rainfall = st.sidebar.number_input('Rainfall (mm)', min_value=0.0)

    data = {
        'N': N,
        'P': P,
        'K': K,
        'temperature': temperature,
        'humidity': humidity,
        'ph': ph,
        'rainfall': rainfall
    }
    features = pd.DataFrame(data, index=[0])
    return features

df = user_input_features()

st.subheader("Input Data")
st.write(df)

if st.button('Predict'):
    prediction = model.predict(df)
    prediction_proba = model.predict_proba(df)

    st.subheader("Crop Recommendation")
    st.write(f"Recommended Crop: {prediction[0]}")

    st.subheader("Prediction Probability")
    st.write(prediction_proba)

